// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import JwtProvider from "./jwt-provider";
import { cookies } from "next/headers";
import { jwtDecode } from "jwt-decode";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// ${geistSans.variable} ${geistMono.variable}

export default async function RootLayout({ children }) {
  const CookieStore = await cookies();
  const token = CookieStore.get("auth_token")?.value || null;
  const decodedToken = token ? jwtDecode(token) : null;
  return (
    <html lang="en">
      <body
        className={`
           antialiased`}
      >
        <JwtProvider decodedToken={decodedToken} token={token}>
          {children}
        </JwtProvider>
      </body>
    </html>
  );
}
